#!/usr/bin/env bash

grep @Library Jenkinsfile
if [ $? -eq 0 ]; then
    printf "[pre-commit hook] Updating branch reference in Jenkinsfile.test to allow self-testing... "
    branch=$(git rev-parse --abbrev-ref HEAD)
    sed -i "s/utils@.*'/utils@${branch}'/" Jenkinsfile*
    git update-index --add Jenkinsfile*
    printf "done.\n"
fi
